### ISSUE TITLE
DNS-ID vs. dNSName

### ISSUE THREAD

**Issue by hannestschofenig** [thomas-fossati/draft-tls13-iot#31]
> If the EUI-64 format is used to identify the subject of an end entity certificate, it MUST be encoded in a subjectAltName of type DNS-ID as a string of the form `HH-HH-HH-HH-HH-HH-HH-HH` where 'H' is one of the symbols '0'-'9' or 'A'-'F'.

Michael:
"DNS-ID" is not how 5280 calls it...
It uses dNSName.
I'm not sure I'd agree with dNSNAME, and you'll see that we tried to get something similar past RH on RFC8994, and wound up having to use otherName.

Thomas:
yeah, this bit reuses bits of RFC6125 glossary, which I thought was established terminology:

> DNS-ID = a subjectAltName entry of type dNSName; see [PKIX]

Michael: 

okay, that's news to me that we can call it the extension DNS-ID. I thought that was the check. And, I don't see how an EUI-64 going to pass a DNS-ID check.

**Comment by mcr** [comment]
closed by #53
