### ISSUE TITLE
Documenting changes from 1.2 to 1.3

### ISSUE THREAD

**Issue by hannestschofenig** [thomas-fossati/draft-tls13-iot#44]
Based on discussion on the TLS mailing list and feedback from JohnM here is a list of items that changed:

>     Rekeying with Ephemeral Diffie-Hellman in a connection (this was used by DTLS/SCTP).
>     Post-Handshake server authentication (this was used by DTLS/SCTP).
>     Rekeying of the exporter secret (this was used by DTLS/SCTP).
>     Flight #4 (this was used by EAP-TLS 1.2).
>     Combining certificates with PSK (this was used by 3GPP)
>     Providing a PSK hint (this was used by 3GPP)

**Comment by thomas-fossati** [comment]
Done in #48
