### ISSUE TITLE
Add text about PQC considerations

### ISSUE THREAD

**Issue by hannestschofenig** [thomas-fossati/draft-tls13-iot#52]
There is ongoing work on doing moving to PQC algorithms. Add text about it.

**Comment by thomas-fossati** [comment]
Maybe consider adding a few more refs, e.g.:

* https://eprint.iacr.org/2023/506.pdf
* https://eprint.iacr.org/2021/1553.pdf

See also https://eprint.iacr.org/search?q=PQC+IoT

**Comment by thomas-fossati** [comment]
MCR, via email:

> Hi, should this section on PQC more explicitely say that Quantum-Safe algorithms are out-of-scope for this document, and recommend against any specific recommendation?
